#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RaffleLive09282021")]
public partial class InventoryDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public InventoryDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RaffleLive09282021ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public InventoryDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InventoryDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InventoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InventoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetWineSearchList")]
	public ISingleResult<GetWineSearchListResult> GetWineSearchList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="WineName", DbType="VarChar(100)")] string wineName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BarCode", DbType="VarChar(100)")] string barCode)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), wineName, barCode);
		return ((ISingleResult<GetWineSearchListResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetInventoryById")]
	public ISingleResult<GetInventoryByIdResult> GetInventoryById([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InventoryID", DbType="Int")] System.Nullable<int> inventoryID)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inventoryID);
		return ((ISingleResult<GetInventoryByIdResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetrecSearchList")]
	public ISingleResult<GetrecSearchListResult> GetrecSearchList([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RecNo", DbType="Int")] System.Nullable<int> recNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BarCode", DbType="VarChar(100)")] string barCode)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), recNo, barCode);
		return ((ISingleResult<GetrecSearchListResult>)(result.ReturnValue));
	}
}

public partial class GetWineSearchListResult
{
	
	private int _Inventory_ID;
	
	private string _Wine_name;
	
	private System.Nullable<int> _Category_id;
	
	private string _BarCode;
	
	private System.Nullable<int> _BottleSize_ID;
	
	private System.Nullable<decimal> _Cost_Wholesale;
	
	private string _Category_Name;
	
	private System.Nullable<int> _Location1_Qty;
	
	private System.Nullable<int> _Location2_Qty;
	
	private System.Nullable<int> _Location3_qty;
	
	private System.Nullable<int> _Heading_ID;
	
	private System.Nullable<int> _SubHeading_ID;
	
	private string _Description;
	
	private string _BottlePrize;
	
	private string _BottleSizeName;
	
	private string _HeadingName;
	
	private string _SubHeadingName;
	
	private System.Nullable<int> _RecNo;
	
	private string _WinelistLineNo;
	
	private System.Nullable<decimal> _WineListCategory;
	
	private string _AlphaSort;
	
	private string _Location1_name;
	
	private string _Location2_name;
	
	private string _Location3_name;
	
	public GetWineSearchListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_ID", DbType="Int NOT NULL")]
	public int Inventory_ID
	{
		get
		{
			return this._Inventory_ID;
		}
		set
		{
			if ((this._Inventory_ID != value))
			{
				this._Inventory_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wine_name", DbType="VarChar(100)")]
	public string Wine_name
	{
		get
		{
			return this._Wine_name;
		}
		set
		{
			if ((this._Wine_name != value))
			{
				this._Wine_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Int")]
	public System.Nullable<int> Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this._Category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="VarChar(1000)")]
	public string BarCode
	{
		get
		{
			return this._BarCode;
		}
		set
		{
			if ((this._BarCode != value))
			{
				this._BarCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSize_ID", DbType="Int")]
	public System.Nullable<int> BottleSize_ID
	{
		get
		{
			return this._BottleSize_ID;
		}
		set
		{
			if ((this._BottleSize_ID != value))
			{
				this._BottleSize_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_Wholesale", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Cost_Wholesale
	{
		get
		{
			return this._Cost_Wholesale;
		}
		set
		{
			if ((this._Cost_Wholesale != value))
			{
				this._Cost_Wholesale = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Name", DbType="VarChar(200)")]
	public string Category_Name
	{
		get
		{
			return this._Category_Name;
		}
		set
		{
			if ((this._Category_Name != value))
			{
				this._Category_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_Qty", DbType="Int")]
	public System.Nullable<int> Location1_Qty
	{
		get
		{
			return this._Location1_Qty;
		}
		set
		{
			if ((this._Location1_Qty != value))
			{
				this._Location1_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_Qty", DbType="Int")]
	public System.Nullable<int> Location2_Qty
	{
		get
		{
			return this._Location2_Qty;
		}
		set
		{
			if ((this._Location2_Qty != value))
			{
				this._Location2_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_qty", DbType="Int")]
	public System.Nullable<int> Location3_qty
	{
		get
		{
			return this._Location3_qty;
		}
		set
		{
			if ((this._Location3_qty != value))
			{
				this._Location3_qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading_ID", DbType="Int")]
	public System.Nullable<int> Heading_ID
	{
		get
		{
			return this._Heading_ID;
		}
		set
		{
			if ((this._Heading_ID != value))
			{
				this._Heading_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHeading_ID", DbType="Int")]
	public System.Nullable<int> SubHeading_ID
	{
		get
		{
			return this._SubHeading_ID;
		}
		set
		{
			if ((this._SubHeading_ID != value))
			{
				this._SubHeading_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottlePrize", DbType="VarChar(50)")]
	public string BottlePrize
	{
		get
		{
			return this._BottlePrize;
		}
		set
		{
			if ((this._BottlePrize != value))
			{
				this._BottlePrize = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSizeName", DbType="VarChar(50)")]
	public string BottleSizeName
	{
		get
		{
			return this._BottleSizeName;
		}
		set
		{
			if ((this._BottleSizeName != value))
			{
				this._BottleSizeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadingName", DbType="VarChar(50)")]
	public string HeadingName
	{
		get
		{
			return this._HeadingName;
		}
		set
		{
			if ((this._HeadingName != value))
			{
				this._HeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHeadingName", DbType="VarChar(50)")]
	public string SubHeadingName
	{
		get
		{
			return this._SubHeadingName;
		}
		set
		{
			if ((this._SubHeadingName != value))
			{
				this._SubHeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecNo", DbType="Int")]
	public System.Nullable<int> RecNo
	{
		get
		{
			return this._RecNo;
		}
		set
		{
			if ((this._RecNo != value))
			{
				this._RecNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinelistLineNo", DbType="VarChar(50)")]
	public string WinelistLineNo
	{
		get
		{
			return this._WinelistLineNo;
		}
		set
		{
			if ((this._WinelistLineNo != value))
			{
				this._WinelistLineNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WineListCategory", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> WineListCategory
	{
		get
		{
			return this._WineListCategory;
		}
		set
		{
			if ((this._WineListCategory != value))
			{
				this._WineListCategory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlphaSort", DbType="VarChar(500)")]
	public string AlphaSort
	{
		get
		{
			return this._AlphaSort;
		}
		set
		{
			if ((this._AlphaSort != value))
			{
				this._AlphaSort = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_name", DbType="VarChar(100)")]
	public string Location1_name
	{
		get
		{
			return this._Location1_name;
		}
		set
		{
			if ((this._Location1_name != value))
			{
				this._Location1_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_name", DbType="VarChar(100)")]
	public string Location2_name
	{
		get
		{
			return this._Location2_name;
		}
		set
		{
			if ((this._Location2_name != value))
			{
				this._Location2_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_name", DbType="VarChar(100)")]
	public string Location3_name
	{
		get
		{
			return this._Location3_name;
		}
		set
		{
			if ((this._Location3_name != value))
			{
				this._Location3_name = value;
			}
		}
	}
}

public partial class GetInventoryByIdResult
{
	
	private int _Inventory_ID;
	
	private string _Wine_name;
	
	private string _BarCode;
	
	private System.Nullable<int> _BottleSize_ID;
	
	private System.Nullable<decimal> _Cost_Wholesale;
	
	private string _Category_Name;
	
	private System.Nullable<int> _Location1_Qty;
	
	private System.Nullable<int> _Location2_Qty;
	
	private System.Nullable<int> _Location3_qty;
	
	private string _BottleSizeName;
	
	private string _HeadingName;
	
	private string _SubHeadingName;
	
	private string _Location1_name;
	
	private string _Location2_name;
	
	private string _Location3_name;
	
	public GetInventoryByIdResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_ID", DbType="Int NOT NULL")]
	public int Inventory_ID
	{
		get
		{
			return this._Inventory_ID;
		}
		set
		{
			if ((this._Inventory_ID != value))
			{
				this._Inventory_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wine_name", DbType="VarChar(100)")]
	public string Wine_name
	{
		get
		{
			return this._Wine_name;
		}
		set
		{
			if ((this._Wine_name != value))
			{
				this._Wine_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="VarChar(1000)")]
	public string BarCode
	{
		get
		{
			return this._BarCode;
		}
		set
		{
			if ((this._BarCode != value))
			{
				this._BarCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSize_ID", DbType="Int")]
	public System.Nullable<int> BottleSize_ID
	{
		get
		{
			return this._BottleSize_ID;
		}
		set
		{
			if ((this._BottleSize_ID != value))
			{
				this._BottleSize_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_Wholesale", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Cost_Wholesale
	{
		get
		{
			return this._Cost_Wholesale;
		}
		set
		{
			if ((this._Cost_Wholesale != value))
			{
				this._Cost_Wholesale = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Name", DbType="VarChar(200)")]
	public string Category_Name
	{
		get
		{
			return this._Category_Name;
		}
		set
		{
			if ((this._Category_Name != value))
			{
				this._Category_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_Qty", DbType="Int")]
	public System.Nullable<int> Location1_Qty
	{
		get
		{
			return this._Location1_Qty;
		}
		set
		{
			if ((this._Location1_Qty != value))
			{
				this._Location1_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_Qty", DbType="Int")]
	public System.Nullable<int> Location2_Qty
	{
		get
		{
			return this._Location2_Qty;
		}
		set
		{
			if ((this._Location2_Qty != value))
			{
				this._Location2_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_qty", DbType="Int")]
	public System.Nullable<int> Location3_qty
	{
		get
		{
			return this._Location3_qty;
		}
		set
		{
			if ((this._Location3_qty != value))
			{
				this._Location3_qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSizeName", DbType="VarChar(50)")]
	public string BottleSizeName
	{
		get
		{
			return this._BottleSizeName;
		}
		set
		{
			if ((this._BottleSizeName != value))
			{
				this._BottleSizeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadingName", DbType="VarChar(50)")]
	public string HeadingName
	{
		get
		{
			return this._HeadingName;
		}
		set
		{
			if ((this._HeadingName != value))
			{
				this._HeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHeadingName", DbType="VarChar(50)")]
	public string SubHeadingName
	{
		get
		{
			return this._SubHeadingName;
		}
		set
		{
			if ((this._SubHeadingName != value))
			{
				this._SubHeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_name", DbType="VarChar(100)")]
	public string Location1_name
	{
		get
		{
			return this._Location1_name;
		}
		set
		{
			if ((this._Location1_name != value))
			{
				this._Location1_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_name", DbType="VarChar(100)")]
	public string Location2_name
	{
		get
		{
			return this._Location2_name;
		}
		set
		{
			if ((this._Location2_name != value))
			{
				this._Location2_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_name", DbType="VarChar(100)")]
	public string Location3_name
	{
		get
		{
			return this._Location3_name;
		}
		set
		{
			if ((this._Location3_name != value))
			{
				this._Location3_name = value;
			}
		}
	}
}

public partial class GetrecSearchListResult
{
	
	private int _Inventory_ID;
	
	private string _Wine_name;
	
	private System.Nullable<int> _Category_id;
	
	private string _BarCode;
	
	private System.Nullable<int> _BottleSize_ID;
	
	private System.Nullable<decimal> _Cost_Wholesale;
	
	private string _Category_Name;
	
	private System.Nullable<int> _Location1_Qty;
	
	private System.Nullable<int> _Location2_Qty;
	
	private System.Nullable<int> _Location3_qty;
	
	private System.Nullable<int> _Heading_ID;
	
	private System.Nullable<int> _SubHeading_ID;
	
	private string _Description;
	
	private string _BottlePrize;
	
	private string _BottleSizeName;
	
	private string _HeadingName;
	
	private string _SubHeadingName;
	
	private System.Nullable<int> _RecNo;
	
	private string _WinelistLineNo;
	
	private System.Nullable<decimal> _WineListCategory;
	
	private string _AlphaSort;
	
	private string _Location1_name;
	
	private string _Location2_name;
	
	private string _Location3_name;
	
	public GetrecSearchListResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inventory_ID", DbType="Int NOT NULL")]
	public int Inventory_ID
	{
		get
		{
			return this._Inventory_ID;
		}
		set
		{
			if ((this._Inventory_ID != value))
			{
				this._Inventory_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wine_name", DbType="VarChar(100)")]
	public string Wine_name
	{
		get
		{
			return this._Wine_name;
		}
		set
		{
			if ((this._Wine_name != value))
			{
				this._Wine_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_id", DbType="Int")]
	public System.Nullable<int> Category_id
	{
		get
		{
			return this._Category_id;
		}
		set
		{
			if ((this._Category_id != value))
			{
				this._Category_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="VarChar(1000)")]
	public string BarCode
	{
		get
		{
			return this._BarCode;
		}
		set
		{
			if ((this._BarCode != value))
			{
				this._BarCode = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSize_ID", DbType="Int")]
	public System.Nullable<int> BottleSize_ID
	{
		get
		{
			return this._BottleSize_ID;
		}
		set
		{
			if ((this._BottleSize_ID != value))
			{
				this._BottleSize_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost_Wholesale", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> Cost_Wholesale
	{
		get
		{
			return this._Cost_Wholesale;
		}
		set
		{
			if ((this._Cost_Wholesale != value))
			{
				this._Cost_Wholesale = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category_Name", DbType="VarChar(200)")]
	public string Category_Name
	{
		get
		{
			return this._Category_Name;
		}
		set
		{
			if ((this._Category_Name != value))
			{
				this._Category_Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_Qty", DbType="Int")]
	public System.Nullable<int> Location1_Qty
	{
		get
		{
			return this._Location1_Qty;
		}
		set
		{
			if ((this._Location1_Qty != value))
			{
				this._Location1_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_Qty", DbType="Int")]
	public System.Nullable<int> Location2_Qty
	{
		get
		{
			return this._Location2_Qty;
		}
		set
		{
			if ((this._Location2_Qty != value))
			{
				this._Location2_Qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_qty", DbType="Int")]
	public System.Nullable<int> Location3_qty
	{
		get
		{
			return this._Location3_qty;
		}
		set
		{
			if ((this._Location3_qty != value))
			{
				this._Location3_qty = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading_ID", DbType="Int")]
	public System.Nullable<int> Heading_ID
	{
		get
		{
			return this._Heading_ID;
		}
		set
		{
			if ((this._Heading_ID != value))
			{
				this._Heading_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHeading_ID", DbType="Int")]
	public System.Nullable<int> SubHeading_ID
	{
		get
		{
			return this._SubHeading_ID;
		}
		set
		{
			if ((this._SubHeading_ID != value))
			{
				this._SubHeading_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(1000)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this._Description = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottlePrize", DbType="VarChar(50)")]
	public string BottlePrize
	{
		get
		{
			return this._BottlePrize;
		}
		set
		{
			if ((this._BottlePrize != value))
			{
				this._BottlePrize = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BottleSizeName", DbType="VarChar(50)")]
	public string BottleSizeName
	{
		get
		{
			return this._BottleSizeName;
		}
		set
		{
			if ((this._BottleSizeName != value))
			{
				this._BottleSizeName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeadingName", DbType="VarChar(50)")]
	public string HeadingName
	{
		get
		{
			return this._HeadingName;
		}
		set
		{
			if ((this._HeadingName != value))
			{
				this._HeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubHeadingName", DbType="VarChar(50)")]
	public string SubHeadingName
	{
		get
		{
			return this._SubHeadingName;
		}
		set
		{
			if ((this._SubHeadingName != value))
			{
				this._SubHeadingName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecNo", DbType="Int")]
	public System.Nullable<int> RecNo
	{
		get
		{
			return this._RecNo;
		}
		set
		{
			if ((this._RecNo != value))
			{
				this._RecNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WinelistLineNo", DbType="VarChar(50)")]
	public string WinelistLineNo
	{
		get
		{
			return this._WinelistLineNo;
		}
		set
		{
			if ((this._WinelistLineNo != value))
			{
				this._WinelistLineNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WineListCategory", DbType="Decimal(18,2)")]
	public System.Nullable<decimal> WineListCategory
	{
		get
		{
			return this._WineListCategory;
		}
		set
		{
			if ((this._WineListCategory != value))
			{
				this._WineListCategory = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlphaSort", DbType="VarChar(500)")]
	public string AlphaSort
	{
		get
		{
			return this._AlphaSort;
		}
		set
		{
			if ((this._AlphaSort != value))
			{
				this._AlphaSort = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location1_name", DbType="VarChar(100)")]
	public string Location1_name
	{
		get
		{
			return this._Location1_name;
		}
		set
		{
			if ((this._Location1_name != value))
			{
				this._Location1_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location2_name", DbType="VarChar(100)")]
	public string Location2_name
	{
		get
		{
			return this._Location2_name;
		}
		set
		{
			if ((this._Location2_name != value))
			{
				this._Location2_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location3_name", DbType="VarChar(100)")]
	public string Location3_name
	{
		get
		{
			return this._Location3_name;
		}
		set
		{
			if ((this._Location3_name != value))
			{
				this._Location3_name = value;
			}
		}
	}
}
#pragma warning restore 1591
